# Generated by Django 2.2.7 on 2019-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
