# Generated by Django 2.2.7 on 2019-11-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0003_auto_20191108_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='mecanico_asignado_nombre',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='trabajos',
            field=models.ManyToManyField(through='mecanica.Trabajo_mecanico', to='mecanica.Trabajo'),
        ),
    ]
