# Generated by Django 2.2.7 on 2019-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0004_auto_20191108_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='trabajos',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='mecanicos',
            field=models.ManyToManyField(through='mecanica.Trabajo_mecanico', to='mecanica.Mecanico'),
        ),
    ]
